version: "2"
services:
  alpinista:
    build:
        context: .
        args:
            - TIMEZONE=Europe/Vienna
    image: local/test_alpinista
    container_name: test_alpinista
    hostname: test_alpinista

networks:
  jenkins:
    name: jenkins

