version: "2"
services:
  registry:
    image: registry:2
    container_name: registry_jenkins_ci
    networks:
      jenkins:
    ports:
      - 5000:5000
    cap_drop:
      - ALL

networks:
  jenkins:
    name: jenkins

